site_name: 20VanillaJSProjects

theme:
    name: dracula
    # logo: /images/logo.png
    favicon: images/favicon.ico

nav:
    - Welcome: index.md
    - Project 01: project01.md
    - Project 02: project02.md
    - Project 03: project03.md
    - Project 04: project04.md
    - Project 05: project05.md
    - Project 06: project06.md
    - Project 07: project07.md
    - Project 08: project08.md
    - Project 09: project09.md
    - Project 10: project10.md
    - Project 11: project11.md
    - Project 12: project12.md
    - Project 13: project13.md
    - Project 14: project14.md
    - Project 15: project15.md
    - Project 16: project16.md
    - Project 17: project17.md
    - Project 18: project18.md
    - Project 19: project19.md
    - Project 20: project20.md

extra_css:
  - css/style.css
